#!/usr/bin/env python3
"""
Script to automate daily product updates for the AkroShopX Shopify store.

This script performs two major tasks:

1. Invokes the existing `pipeline.py` scraper to fetch product data from
   suppliers (AliExpress and Wish) and generate a Shopify‑compatible CSV
   file. The `pipeline.py` script must be present in the same repository
   and accept the arguments used below. Adjust the arguments as needed
   for your setup (e.g. number of products, language, output location).

2. Reads the generated CSV and creates or updates products on Shopify via
   the Admin REST API. To authenticate, two environment variables must
   be provided in the execution environment or GitHub Actions secrets:
     - ``SHOPIFY_SHOP``: your Shopify shop domain (e.g.
       ``akroshopx.myshopify.com``)
     - ``SHOPIFY_ADMIN_API_ACCESS_TOKEN``: an Admin API access token with
       permission to create and update products.  See the Shopify docs for
       instructions on generating this token.

The CSV generated by ``pipeline.py`` is expected to have at least the
following columns: ``Title``, ``Body (HTML)``, ``Vendor``, ``Type``,
``Tags``, ``Variant SKU``, ``Variant Price``, and optionally
``Image Src``.  Additional columns will be ignored.

Running this script repeatedly without idempotency logic will create
duplicate products.  For production usage you should enhance the logic
below to check for existing products (e.g. by SKU) and update them
instead of creating new ones.  This example focuses on clarity and
conciseness for demonstration purposes.
"""

import csv
import json
import os
import subprocess
import sys
from pathlib import Path

import requests


def run_pipeline(max_per_category: int = 100, languages: str = "fr,en", out_csv: str = "data/akroshopx_products.csv") -> None:
    """Invoke the pipeline.py script to generate a CSV of products.

    Parameters
    ----------
    max_per_category : int
        Number of products to fetch per category.
    languages : str
        Comma‑separated list of language codes for product content.
    out_csv : str
        Destination path for the generated CSV file.
    """
    script_path = Path(__file__).with_name("pipeline.py")
    if not script_path.exists():
        raise FileNotFoundError(
            f"pipeline.py not found in {script_path.parent}. Ensure the scraper script exists."
        )
    cmd = [
        sys.executable,
        str(script_path),
        "--max-per-category",
        str(max_per_category),
        "--lang",
        languages,
        "--out",
        out_csv,
    ]
    print(f"Running pipeline: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("pipeline.py failed with output:")
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        raise RuntimeError("pipeline.py execution failed")
    print("pipeline.py completed successfully")


def create_or_update_products_from_csv(csv_path: str) -> None:
    """Read a CSV of products and create them on Shopify via the REST API.

    Environment variables ``SHOPIFY_SHOP`` and
    ``SHOPIFY_ADMIN_API_ACCESS_TOKEN`` must be set.
    """
    shop = os.environ.get("SHOPIFY_SHOP")
    token = os.environ.get("SHOPIFY_ADMIN_API_ACCESS_TOKEN")
    if not shop or not token:
        raise EnvironmentError(
            "SHOPIFY_SHOP and SHOPIFY_ADMIN_API_ACCESS_TOKEN environment variables must be set"
        )
    api_endpoint = f"https://{shop}/admin/api/2025-01/products.json"
    headers = {
        "Content-Type": "application/json",
        "X-Shopify-Access-Token": token,
    }
    with open(csv_path, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)
        for idx, row in enumerate(reader, start=1):
            # Basic product structure; extend as needed
            product_data = {
                "product": {
                    "title": row.get("Title") or row.get("title"),
                    "body_html": row.get("Body (HTML)") or row.get("body_html"),
                    "vendor": row.get("Vendor") or row.get("vendor"),
                    "product_type": row.get("Type") or row.get("product_type"),
                    "tags": [tag.strip() for tag in (row.get("Tags", "").split(",")) if tag.strip()],
                    "variants": [
                        {
                            "price": row.get("Variant Price") or row.get("price"),
                            "sku": row.get("Variant SKU") or row.get("sku"),
                        }
                    ],
                }
            }
            # Include image if available
            image_url = row.get("Image Src") or row.get("Image")
            if image_url:
                product_data["product"]["images"] = [
                    {"src": image_url}
                ]
            # Send request to Shopify
            try:
                response = requests.post(
                    api_endpoint, headers=headers, data=json.dumps(product_data)
                )
                response.raise_for_status()
            except requests.RequestException as e:
                # Log error and continue with next product
                print(f"Error creating product {product_data['product']['title']}: {e}")
                continue
            print(f"Created product {idx}: {product_data['product']['title']}")


def main() -> None:
    """Entry point for script execution."""
    # Determine the maximum number of products per category and language list from
    # environment variables. GitHub Actions passes these through via workflow inputs.
    max_per_category_env = os.environ.get("MAX_PER_CATEGORY")
    languages_env = os.environ.get("LANGUAGES")
    try:
        max_per_category = int(max_per_category_env) if max_per_category_env else 100
    except ValueError:
        max_per_category = 100
    languages = languages_env or "fr,en"
    # Define output CSV path relative to repository root
    output_csv = os.path.join("data", "akroshopx_products.csv")
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    # Run the scraper pipeline
    run_pipeline(max_per_category=max_per_category, languages=languages, out_csv=output_csv)
    # Create or update products on Shopify
    create_or_update_products_from_csv(output_csv)


if __name__ == "__main__":
    main()
